spring:
 data:
   mongodb:
     #username: ${MONGO_USER}
     #password: ${MONGO_PASSWORD}
     database: ${MONGO_DATABASE}
     port: ${MONGO_PORT}
     host: ${MONGO_HOST}
 application:
    name: analyticsservice
server:
 port: 9099
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka